name: google_maps_flutter_web_integration_tests
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface:
    git:
      url: https://github.com/ouedyan/flutter-packages.git
      path: packages/google_maps_flutter/google_maps_flutter_platform_interface
  google_maps_flutter_web:
    path: ../
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  google_maps: ^8.0.0
#  google_maps_flutter: ^2.2.0 # Needed for projection_test.dart
  google_maps_flutter:
    git:
      url: https://github.com/ouedyan/flutter-packages.git
      path: packages/google_maps_flutter/google_maps_flutter
  http: ^1.2.2
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  assets:
    - assets/

dependency_overrides:
  # Override the google_maps_flutter dependency on google_maps_flutter_web.
  # TODO(ditman): Unwind the circular dependency. This will create problems
  # if we need to make a breaking change to google_maps_flutter_web.
  google_maps_flutter_web:
    path: ../
